### ISSUE TITLE
Server returns "BAD Missing Sort criteria" when attempting to sort

### ISSUE THREAD

**Issue by y0ast** [emersion/go-imap-sortthread#13]
Hi,

I call my email server (fastmail) as follows and obtain a BAD response:
```
UID SORT ("SUBJECT") "UTF-8" 1:*
BAD Missing Sort criteria
```

`SupportSort()` returns `true` however.

From https://tools.ietf.org/html/rfc5256 it seems that there's not much to this command and this should just work.

Is there anything I can debug on go-imap-sortthread side, or is this a server bug?

**Comment by foxcpp** [comment]
Would removing quotes around SUBJECT fix it? They are not supposed to be here, according to ABNF.
```
UID SORT (SUBJECT) "UTF-8" 1:*
```

**Comment by foxcpp** [comment]
https://www.github.com/emersion/go-imap-sortthread/tree/master/sortthread.go

In formatSortCriterion, the c.Field should be wrapped in imap.RawString.
