### ISSUE TITLE
Cannot request ALL as search criteria

### ISSUE THREAD

**Issue by romuloalves** [emersion/go-imap-sortthread#5]
I want to use the `UID THREAD` command, but I would like to use it like this:
`UID THREAD REFERENCES "UTF-8" ALL`

I could not find a way to use the "ALL" as search criteria.

Thanks for the help!

**Comment by emersion** [comment]
Hmm, indeed that's missing. I think we should allow the search criteria to be nil, and format this as ALL. And probably allow an empty search criteria to mean ALL too.

**Comment by romuloalves** [comment]
Closed because of https://github.com/emersion/go-imap/pull/330.
